### ISSUE TITLE
DynamoDB - Add tagging support

### ISSUE THREAD

**Issue by pauldeden** [byu-oit/handel#194]
The use case is that BYU will be tracking costs and other things with tags on DynamoDB.

**Comment by pauldeden** [comment]
I didn't see tagging support at https://handel.readthedocs.io/en/latest/supported-services/dynamodb.html

**Comment by dsw88** [comment]
I didn't add tags to DynamoDB because they're not yet supported in CloudFormation. You can add them manually outside of CloudFormation, but it was just a bit more work so I decided not to do them until someone asked for them.

I've added this issue to the roadmap and we'll get support added for DynamoDB tags.

**Comment by pauldeden** [comment]
Makes sense and thank you.

**Comment by ndpete** [comment]
@pauldeden This feature is now implemented. You can add tags like most other services in handel. See the Handel [documentation](https://handel.readthedocs.io/en/latest/supported-services/dynamodb.html) for examples.

**Comment by pauldeden** [comment]
Excellent thank you
