### ISSUE TITLE
Alexa - Add the Alexa Skills Kit as an Event Producer for Lambda functions

### ISSUE THREAD

**Issue by pauldeden** [byu-oit/handel#206]
In order for a Lambda function to be used as an Alexa Skills Kit skill one needs to add a 'trigger' to the lambda function.  Here is a screenshot of the page in the console to do it.
<img width="1244" alt="screen shot 2017-07-13 at 12 41 36 pm" src="https://user-images.githubusercontent.com/4304479/28182297-e98b2632-67c8-11e7-865f-38326c32ff9e.png">

It's not a difficult process but in order for developers to not have to remember to do manually that every time they create a new lambda function with Handel that will be an Alexa skill, I'm requesting that the Alexa Skills Kit be added as a new Handel service that can function as an event producer for Lambda functions created by Handel.

The new Alexa Skills Kit service probably wouldn't need any options.

**Comment by dsw88** [comment]
Added to the backlog.

**Comment by ndpete** [comment]
I've been looking into the cloud formation side of doing this. To add that trigger I believe you only need to create a LambdaPermision see [here](https://developer.amazon.com/blogs/post/Tx27NAUCY0KQ34D/Rapidly-Create-Your-Alexa-Skill-Backend-with-AWS-CloudFormation) and [here](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-permission.html) for more info.

Would we need/want to create a whole new service with no options or maybe just an optional boolean parameter for the lambda service? ie `alexa_skill_kit: true` and if that parameter is true then create the lambda permission resource to add that trigger?

**Comment by dsw88** [comment]
I would vote having a new service rather than embedding it into the Lambda parameters. The service itself would do practically nothing, since it only exists to integrate with Lambda. The reason for having it as a separate service, however, is so that if more things integrate with the Alexa Skills Kit in the future we can easily support that.

As for the integration, you're correct that a lambda permission is all that is required to set this up. We actually do those outside the CloudFormation stack for the Lambda in the ConsumeEvents phase, because multiple people might potentially need to add and remove permissions dynamically, which CloudFormation has a hard time with since it often wants to overwrite whatever is currently configured on the service to make it conform to the template.

Since these added permissions are attached to the Lambda, when you delete the Lambda stack, all the added permissions go away too. This means this approach doesn't have any issues with leaving behind orphaned resources.

**Comment by pauldeden** [comment]
Thumbs up!  Thanks.

**Comment by dsw88** [comment]
This feature has been implemented, thanks to @ndpete for implementing it! See the docs at http://handel.readthedocs.io/en/latest/supported-services/alexaskillkit.html for information on configuring a Lambda with the Alexa Skills Kit.

**Comment by pauldeden** [comment]
Thanks!
