### ISSUE TITLE
Elasticache - subnet group contents should not include public subnets or should be configurable

### ISSUE THREAD

**Issue by brentmoore** [byu-oit/handel#331]
Handel includes all subnets defined in the account config file in the subnet group created during deployment, including the public subnets. Since Redis by default doesn't use passwords having the caches available in public subnets doesn't seem safe. Either we should not add the public subnets to the subnet group or create a configuration option to specify which subnets (public, private, data) to add to the subnet group. 

Once Redis is deployed you cannot remove a subnet from the group.

**Comment by dsw88** [comment]
I think Handel only creates subnet groups when using the default VPC; if you provide an account config file, one of the required fields to use Redis is providing the name of an elasticache subnet group to use. Basically if you provide an account config file, you're required to have already set up your network, including subnet groups.

In the case of the default VPC, the subnets are all public subnets, so we have to use them for public, private, and data. However, Handel wires things up pretty tightly with security groups, so even in that case the Redis instance is not granted ingress from anything other than the services consuming it inside the application. So even though it has a public IP, the firewall around it doesn't allow ingres from anywhere other than what was requested.

So I think we're fine, but I may have missed something. Let me know how the above sounds to you.

**Comment by dsw88** [comment]
@brentmoore Did my previous comments help clarify things on this issue?

**Comment by dsw88** [comment]
Hopefully my previous comments helped clarify things. Just to recap, we only create a subnet group when using the default VPC, otherwise we require the user to specify one for their custom VPCs. In the case of the default VPC, we have to use public subnets for the subnet groups because that's all it has. However, security group wiring is sufficient to lock down Redis access to just the resources that use it. 

Let me know if there are further questions, but for now I'm closing this issue.
