### ISSUE TITLE
ECS - Create an ECS cluster to be used in current or separate handel files

### ISSUE THREAD

**Issue by yoshutch** [byu-oit/handel#342]
Maybe add support for creating just the ECS cluster instead of a service to be run on an ECS cluster. An ECS service can then specify which ECS cluster to deploy to, if none is supplied it could default to what it does now (create a default cluster per service) etc.
I know that we have Fargate support now, which is kind of like this, but right now it's still in a sort of BETA usage and only on us-east-1 region.
Mainly this would allow for multiple applications/pipelines to use the same ECS cluster when deploying an ECS service.

**Comment by dsw88** [comment]
Something does need to be added to support this. I'm putting this in the V0 project and am going to prioritize it pretty high. Hopefully I or someone else will be able to take it to work on soon.

**Comment by dsw88** [comment]
I think we're leaning towards implementing this as a service extension, which means this issue depends on #302

**Comment by dsw88** [comment]
I think this is a great idea, but I'm not sure it belongs in core Handel since it relies on externally created resources not managed by the deployment itself. Additionally, it would be a bit of work and we have good Fargate support now.

This is a great candidate for an extension, and you can now write extensions to Handel. Here is the initial documentation for writing an extension: http://handel.readthedocs.io/en/latest/extensions/writing-extensions.html. It's a new page, so feel free to provide feedback on how it can be improved.
