### ISSUE TITLE
DynamoDB - allow global indexes to copy all attributes

### ISSUE THREAD

**Issue by yoshutch** [byu-oit/handel#345]
It would be nice to allow the global secondary indexes to copy all attributes using the ProjectionType: ALL in the CF template instead of having to list out all the attributes manually.

**Comment by dsw88** [comment]
Great idea, this should probably be added. Be aware that this will basically double the cost of your table if I recall, since a global index is basically a copy into a new table containing those attributes. We'll probably want to put a note informing people of that in the docs when this support is added.
