### ISSUE TITLE
Handel needs to apply tags to the lambdas that are automatically deployed under the covers

### ISSUE THREAD

**Issue by bwinterton** [byu-oit/handel#360]
Handel deploys several lambdas in different scenarios to manage different resources or provide additional functionality. These lambdas include (but are not limited to):
- `HandelEcsAutoScalingLambda`
- `HandelEcsDrainingLambda`
- `HandelSlackNotify`
- etc

We need to have a way to apply tags to these Lambdas in order to meet enterprise requirements.

**Comment by bwinterton** [comment]
This also plays into #332

**Comment by ndpete** [comment]
Looking through the different accounts I think most if not all the handel deployed lambdas

**Comment by ThatJoeMoore** [comment]
This really raises two questions:

1) What tags do we apply?
2) How do we define the values?

We can't, for example, use the 'app' value from the Handel stack that spins up the shared resource the first time, because multiple Handel stacks will re-use the same resources.  Perhaps this is yet another thing that belongs in the [VPC/Account config file](https://handel.readthedocs.io/en/latest/handel-basics/account-config-file.html)?

I think that, if we included the desired tags in the account config file, we could have a nice, simple, extensible way to apply tags to these global resources.

**Comment by bwinterton** [comment]
That is essentially what @ndpete and I were thinking the other day, that maybe these tags are best configured in the Account Config file.

**Comment by dsw88** [comment]
I agree, this is something that should be supported via optional parameters in the Account Config File, because different people will want different tags applied to these resources.

How about something like this in the Account Config File?
```
handel_resource_tags:
  <key>: <value>
```

These would be applied to any resource that Handel creates to support any of the service provisioners, but NOT the resources created from an application's Handel file. Handel would still tag those based on the configuration in that application's Handel file.

**Comment by ThatJoeMoore** [comment]
I've got a PR in for this (#369).
