### ISSUE TITLE
ECS (including Fargate) - create ECR repos automatically

### ISSUE THREAD

**Issue by bradleyreneer** [byu-oit/handel#421]
We would like to create these repositories using infrastructure as code instead of manually.

**Comment by dsw88** [comment]
Handel can't really do anything about this since it is solely a deploy tool, so by the time you execute Handel the build is over and it's too late to create resources like an ECR repo for the build.

Handel-CodePipeline does grant permissions to the build phase to do these repository creations though. You can do something like this in your buildspec file to create the repository:

```
imageName=storage-ws

if ! aws ecr describe-repositories --repository-names $imageName &>/dev/null; then
  echo "Creating ECS Repository"
  aws ecr create-repository --repository-name $imageName
fi
```

We could certainly add something more formal to Handel-CodePipeline's build phase type to configure ECR repositories in your handel-codepipeline.yml file. I haven't ever added it yet because I just always include the above lines in my buildspec file.

**Comment by dsw88** [comment]
I'll close this issue in Handel, but feel free to open one up in Handel-CodePipeline if the above suggestion for your buildspec file isn't desired.
